fingers crossed!

diff --git a/version_check/action.yml b/version_check/action.yml
--- a/version_check/action.yml
+++ b/version_check/action.yml
@@ -1,13 +1,6 @@
 name: Version Check
 description: "Verify that the PR has a valid version label"
 inputs:
-  pr_labels:
-    description: "Labels from the current PR."
-    required: true
-  version_labels:
-    description: "Valid version labels."
-    required: false
-    default: '["major", "minor", "patch", "no version"]'
   pr_label_major:
     description: "PR label name to use for bumping the major version."
     required: false
@@ -27,67 +20,40 @@ inputs:
 
 runs:
   using: "composite"
-
   steps:
     - name: Check Labels
       shell: bash
       env:
+        PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
         MAJOR_LABEL: ${{ inputs.pr_label_major }}
         MINOR_LABEL: ${{ inputs.pr_label_minor }}
         PATCH_LABEL: ${{ inputs.pr_label_patch }}
         NO_RELEASE_LABEL: ${{ inputs.pr_label_norelease }}
-        # PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
-        PR_LABELS: ${{ inputs.pr_labels }}
-        VERSION_LABELS: ${{ inputs.version_labels }}
-        VERSION_LABELS_2: ${{ toJson(inputs.version_labels) }}
-        EVENT: ${{ toJson(github.event) }}
         LABEL_COUNT: 0
         LABEL: ""
       run: |
-        set +e
-        echo "MAJOR_LABEL: ${MAJOR_LABEL}"
-        echo "MINOR_LABEL: ${MINOR_LABEL}"
-        echo "PATCH_LABEL: ${PATCH_LABEL}"
-        echo "NO_RELEASE_LABEL: ${NO_RELEASE_LABEL}"
-        echo "PR_LABELS: ${PR_LABELS}"
-        echo "VERSION_LABELS: ${VERSION_LABELS}"
-        echo "VERSION_LABELS_2: ${VERSION_LABELS_2}"
-        echo "INPUTS: ${{ toJson(inputs) }}"
-
+        VERSION_LABELS=( ${MAJOR_LABEL}, ${MINOR_LABEL}, ${PATCH_LABEL}, ${NO_RELEASE_LABEL})
         for version in ${VERSION_LABELS[@]}; do
-        echo "version=${version}"
+          echo "checking for version: ${version}"
+          for label in ${PR_LABELS[@]}; do
+            echo "comparing label: ${label}"
+            if [[ ${version} == ${label} ]]; then
+              LABEL_COUNT=$((LABEL_COUNT+1))
+              LABEL=${label}
+            fi
+          done
         done
-        for label in ${PR_LABELS[@]}; do
-        echo "label=${label}"
-        done
+        echo "LABEL_COUNT=${LABEL_COUNT}"
+        echo "LABEL=${LABEL}"
 
-        echo "EVENT: ${EVENT}"
-        echo "set:"
-        set
-        echo "env: ${{ toJson(env) }}"
-
-
-        # for version in ${VERSION_LABELS[@]}; do
-        #   echo "checking for version: ${version}"
-        #   for label in ${PR_LABELS[@]}; do
-        #     echo "comparing label: ${label}"
-        #     if [[ ${version} == ${label} ]]; then
-        #       LABEL_COUNT=$((LABEL_COUNT+1))
-        #       LABEL=${label}
-        #     fi
-        #   done
-        # done
-        # echo "LABEL_COUNT=${LABEL_COUNT}"
-        # echo "LABEL=${LABEL}"
-
-        # if [[ ${LABEL_COUNT} == 1 ]]; then
-        #   echo "::notice::Version verified!"
-        #   echo "::notice::Successfully identified version label for PR: ${LABEL}"
-        # elif [[ ${LABEL_COUNT} < 1 ]]; then
-        #   echo "::error::No version label detected!"
-        #   echo "::error::PRs require one of the following labels: major, minor, patch, no version"
-        # elif [[ ${LABEL_COUNT} > 1 ]]; then
-        #   echo "::error::Too many versions detected!"
-        #   echo "::error::Remove extra version label(s). Only one of the following is allowed: major, minor, patch, no version"
-        # fi
-        # exit $((LABEL_COUNT-1))
+        if [[ ${LABEL_COUNT} == 1 ]]; then
+          echo "::notice::Version verified!"
+          echo "::notice::Successfully identified version label for PR: ${LABEL}"
+        elif [[ ${LABEL_COUNT} < 1 ]]; then
+          echo "::error::No version label detected!"
+          echo "::error::PRs require one of the following labels: ${VERSION_LABELS}"
+        elif [[ ${LABEL_COUNT} > 1 ]]; then
+          echo "::error::Too many versions detected!"
+          echo "::error::Remove extra version label(s). Only one of the following is allowed: ${VERSION_LABELS}"
+        fi
+        exit $((LABEL_COUNT-1))
